//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test942.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComfortEntities1 : DbContext
    {
        public ComfortEntities1()
            : base("name=ComfortEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiscountPartners> DiscountPartners { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FamilyStatus> FamilyStatus { get; set; }
        public virtual DbSet<Health> Health { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsMaterial> ProductsMaterial { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<ProductWorkshop> ProductWorkshop { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<RequestDetails> RequestDetails { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SaleHistory> SaleHistory { get; set; }
        public virtual DbSet<SalePoint> SalePoint { get; set; }
        public virtual DbSet<SizeUpakovka> SizeUpakovka { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<TypeOfBusiness> TypeOfBusiness { get; set; }
        public virtual DbSet<TypeWorkshop> TypeWorkshop { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
