//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test942.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsMaterial = new HashSet<ProductsMaterial>();
            this.ProductWorkshop = new HashSet<ProductWorkshop>();
            this.RequestDetails = new HashSet<RequestDetails>();
            this.SaleHistory = new HashSet<SaleHistory>();
        }
    
        public int Id_product { get; set; }
        public string Articul { get; set; }
        public string NameProduct { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<int> Id_size { get; set; }
        public string WeightNETTO { get; set; }
        public string WeightBRUTTO { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> Id_type { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual SizeUpakovka SizeUpakovka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterial> ProductsMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkshop> ProductWorkshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetails> RequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleHistory> SaleHistory { get; set; }
    }
}
