//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test942.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestDetails = new HashSet<RequestDetails>();
        }
    
        public int Id_request { get; set; }
        public Nullable<int> Id_partner { get; set; }
        public Nullable<int> Manager { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Id_status { get; set; }
        public Nullable<decimal> TotalAmountReq { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetails> RequestDetails { get; set; }
    }
}
