//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test942.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalePoint()
        {
            this.SaleHistory = new HashSet<SaleHistory>();
        }
    
        public int Id_point { get; set; }
        public string NamePoint { get; set; }
        public string AdressPoint { get; set; }
        public Nullable<int> Id_partner { get; set; }
    
        public virtual Partners Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleHistory> SaleHistory { get; set; }
    }
}
