//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test942.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workshop()
        {
            this.ProductWorkshop = new HashSet<ProductWorkshop>();
        }
    
        public int Id_workshop { get; set; }
        public string NameWorkshop { get; set; }
        public Nullable<int> CountPeople { get; set; }
        public Nullable<int> Id_type { get; set; }
        public Nullable<int> Id_employee { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkshop> ProductWorkshop { get; set; }
        public virtual TypeWorkshop TypeWorkshop { get; set; }
    }
}
